services:
  app:
    build: .
    container_name: lauk-restoran-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lauk-restoran-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: basketismylife
      MYSQL_DATABASE: lauk_restoran
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lauk-restoran-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: basketismylife
    depends_on:
      - db

volumes:
  db_data:
